### ISSUE TITLE
Broken Docs Link

### ISSUE THREAD

**Issue by DLu** [yale-sean/social_sim_unity#1]
https://github.com/yale-sean/social_sim_docs (linked to in README.md)

**Comment by han-kyung-min** [comment]
Hello, 

Is this issue has been resolved yet ?
I am having the same problem. It hard to use the simulator since there is no manual docs.

**Comment by nathantsoi** [comment]
The source code for the docs are at the link above, the documentation itself is available here https://sean.interactive-machines.com/docs/architecture/ and here https://sean.interactive-machines.com/tutorials/running/.

Sorry for the slow response, please feel free to email me with any other questions: nathan.tsoi@yale.edu
