### ISSUE TITLE
Expected Behavior?

### ISSUE THREAD

**Issue by DLu** [yale-sean/social_sim_unity#2]
I'm a little confused what is supposed to happen when the Unity scene starts. 
 * I open the Lab scene in the Unity Editor
 * I press the play button at the top
 * Robot appears in the center of the room, people start walking and the timer is counting down
 * (Good so far)
 * After a few seconds, the robot will magically transport to somewhere else in the room, sometimes above the ground. 

Is that the expected behavior when the robot gets sufficiently close to the goal?

**Comment by nathantsoi** [comment]
Yes. The robot "transporting" is the start of a new "Task" (Start Location A to Goal Location B). The choice of the robot task in the SEAN UI defines how the start and goal locations are chosen. 

See https://sean.interactive-machines.com/docs/architecture/ for more information about the task.
