### ISSUE TITLE
depth_synchronizer.py Issue

### ISSUE THREAD

**Issue by psefia** [yale-sean/social_sim_unity#7]
To whom it may concern,

Good afternoon! My name is Paula, and I am a college student working with Professor Zhi Tan on setting up SEAN on my machine (Windows 11, using Ubuntu 20.04.6 LTS to run tmuxinator). I was able to get the simulation to work on Unity, but I ran into rviz errors and tmuxinator errors. 

- When I ran the simulation and navigated to rviz, in the displays tab when I opened the Image dropdown, the Image section says No Image received
- When launching the depthtoscan launch file, the depth_synchronizer.py file did not process successfully (error on line 75 ( img[:,:,3] = np.bitwise_and(img[:,:,3], np.full((img.shape[0],img.shape[1]), 0x01111111, np.uint8))) and the error is that "NoneType object is not subscriptable". Professor Tan and I deduced that the issue is line 74 (img = cv2.imdecode(arr, cv2.IMREAD_UNCHANGED)), because the data stored into img after this line of code is run is None, hence why the NoneType object is not subscriptable
- We noticed that on line 73 (where arr is initialized ( arr = np.frombuffer(compressed_image.data, np.uint8))) the value of arr is a bunch of arrays that store the singular value 205 
([205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
[205 205 205 ... 205 205 205]
etc).

We were wondering if we could have someone look into these issues so we can continue the process of getting the simulator, rviz, and tmuxinator working properly on my machine.

Thank you so much!

**Comment by nathantsoi** [comment]
Hi @psefia, please [email me](mailto:nathan.tsoi@yale.edu) and we can set up a time to debug or try out the new version. I invited you to the new repos (there are 3) and I am happy to help you set this up and make sure it's working.
